apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-recipient

spec:
  selector:
    matchLabels:
      app: micro-recipient
  replicas: 3

  template:
    metadata:
      labels:
        app: micro-recipient
    spec:
      containers:
        - name: micro-recipient
          image: micro-recipient:lts
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
