apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-collector

spec:
  selector:
    matchLabels:
      app: micro-collector
  replicas: 3

  template:
    metadata:
      labels:
        app: micro-collector
    spec:
      containers:
        - name: micro-collector
          image: micro-collector:lts
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
