spring:
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 15672
    exchange: notification.exchange
    queue: notification.queue
    routingkey: notification.routingkey
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always