apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-sender

spec:
  selector:
    matchLabels:
      app: micro-sender
  replicas: 3

  template:
    metadata:
      labels:
        app: micro-sender
    spec:
      containers:
        - name: micro-sender
          image: micro-sender:lts
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
